/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Invoice.View;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author admin
 */
public class pnlInvoice extends javax.swing.JPanel {

    /**
     * Creates new form pnlInvoice
     */
    public pnlInvoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tblAddInvoice = new javax.swing.JButton();
        btnEditInvoice = new javax.swing.JButton();
        btnDeleteInvoice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        jToolBar1.setRollover(true);

        tblAddInvoice.setText("Tạo hóa đơn");
        tblAddInvoice.setFocusable(false);
        tblAddInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblAddInvoice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tblAddInvoice);

        btnEditInvoice.setText("Sửa hóa đơn");
        btnEditInvoice.setFocusable(false);
        btnEditInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditInvoice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEditInvoice);

        btnDeleteInvoice.setText("Xóa hóa đơn");
        btnDeleteInvoice.setFocusable(false);
        btnDeleteInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteInvoice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDeleteInvoice);

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HD001", "1", "Trịnh Thị Ngọc Ánh", "Hóa đơn điện tháng 1", "900000", "02/02/2020"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tháng", "Tên khách hàng", "Diễn giải", "Số tiền", "Ngày tạo"
            }
        ));
        jScrollPane1.setViewportView(tblInvoice);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hóa đơn");

        jButton4.setText("tìm kiếm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn", "Tháng", "Trạng thái", "Tên khách hàng" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnDeleteInvoice() {
        return btnDeleteInvoice;
    }

    public void setBtnDeleteInvoice(JButton btnDeleteInvoice) {
        this.btnDeleteInvoice = btnDeleteInvoice;
    }

    public JButton getBtnEditInvoice() {
        return btnEditInvoice;
    }

    public void setBtnEditInvoice(JButton btnEditInvoice) {
        this.btnEditInvoice = btnEditInvoice;
    }

    public JButton getTblAddInvoice() {
        return tblAddInvoice;
    }

    public void setTblAddInvoice(JButton tblAddInvoice) {
        this.tblAddInvoice = tblAddInvoice;
    }

    public JTable getTblInvoice() {
        return tblInvoice;
    }

    public void setTblInvoice(JTable tblInvoice) {
        this.tblInvoice = tblInvoice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteInvoice;
    private javax.swing.JButton btnEditInvoice;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton tblAddInvoice;
    private javax.swing.JTable tblInvoice;
    // End of variables declaration//GEN-END:variables
}
