/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.View;

import Customer.View.pnlCustomer;
import Invoice.View.pnlInvoice;
import java.awt.Window;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author admin
 */
public class frmMain extends javax.swing.JFrame {

    public pnlCustomer getPnlCustomer() {
        return pnlCustomer;
    }

    public void setPnlCustomer(pnlCustomer pnlCustomer) {
        this.pnlCustomer = pnlCustomer;
    }

    

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JMenu getMnuCaculate() {
        return mnuCaculate;
    }

    public void setMnuCaculate(JMenu mnuCaculate) {
        this.mnuCaculate = mnuCaculate;
    }

    
    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }
  
    public JMenuItem getjMenuItem5() {
        return jMenuItem5;
    }

    public void setjMenuItem5(JMenuItem jMenuItem5) {
        this.jMenuItem5 = jMenuItem5;
    }

    public JMenuItem getjMenuItem6() {
        return jMenuItem6;
    }

    public void setjMenuItem6(JMenuItem jMenuItem6) {
        this.jMenuItem6 = jMenuItem6;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }


    public pnlInvoice getPnlInvoice1() {
        return pnlInvoice1;
    }

    public void setPnlInvoice1(pnlInvoice pnlInvoice1) {
        this.pnlInvoice1 = pnlInvoice1;
    }

    public pnlInvoice getPnlInvoice2() {
        return pnlInvoice2;
    }

   
    
    /**
     * Creates new form FRMMain
     */
    public void setPnlInvoice2(pnlInvoice pnlInvoice2) {    
        this.pnlInvoice2 = pnlInvoice2;
    }

    public frmMain() {
        initComponents();

    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlCustomer = new Customer.View.pnlCustomer();
        pnlInvoice1 = new Invoice.View.pnlInvoice();
        pnlInvoice2 = new Invoice.View.pnlInvoice();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuCaculate = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Khách hàng", pnlCustomer);

        javax.swing.GroupLayout pnlInvoice1Layout = new javax.swing.GroupLayout(pnlInvoice1);
        pnlInvoice1.setLayout(pnlInvoice1Layout);
        pnlInvoice1Layout.setHorizontalGroup(
            pnlInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInvoice2, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        pnlInvoice1Layout.setVerticalGroup(
            pnlInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoice1Layout.createSequentialGroup()
                .addComponent(pnlInvoice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Hóa đơn", pnlInvoice1);

        jMenu2.setText("Tài khoản");

        jMenuItem5.setText("Đổi mật khẩu");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Đăng xuất");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        mnuCaculate.setText("Tính tiền điện");
        jMenuBar1.add(mnuCaculate);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu mnuCaculate;
    private Customer.View.pnlCustomer pnlCustomer;
    private Invoice.View.pnlInvoice pnlInvoice1;
    private Invoice.View.pnlInvoice pnlInvoice2;
    // End of variables declaration//GEN-END:variables
}
